# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 3 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Bucharest
          config_twemoji: yes

          # languages plugin
          plugin_languages: yes
          plugin_languages_ignored: 0

          # contributors plugin
          plugin_contributors: yes
          plugin_contributors_contributions: yes

          # achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # activity plugin
          plugin_activity: yes
          plugin_activity_days: 100
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # calendar plugin
          plugin_calendar: yes
          plugin_calendar_limit: 3

          # code plugin
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

          # notable plugin
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # people plugin
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          # topics plugin
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars

          # wakatime plugin
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current

          # repositories plugin
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random

          # stars plugin
          plugin_stars: yes
          plugin_stars_limit: 4
